import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../styles/globals.css';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components';

const poppins = Poppins({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800', '900'],
});

// TODO: create custom meta data

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'h-svh w-svw antialiased space-y-0 overflow-x-hidden',
          poppins.variable,
        )}
      >
        <Navbar />

        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
